[default]
workshop = [
    "450814997",  # CBA_A3
    "2369477168", # Advanced Dev Tools
    "623475643",  # 3DEN Enhanced
]
presets = []
dlc = []
optionals = []
parameters = []

[ace]
extends = "default"
workshop = [
    "463939057", # ACE
]

# This is only for HEMTT development purposes
[photoshoot]
dev_mission = "D:\\GitHub\\HEMTT-Repro\\.hemtt\\missions\\photoshoot.VR"