name = "HEMTT Repro"
author = "DartRuffian"
prefix = "hmt"
mainprefix = "z"

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "logo_hmt.png",
    "logo_hmt_ca.paa",
    "LICENSE.md",
    "README.md",
]
exclude = []

[properties]
author = "DartRuffian"